apiVersion: v1
kind: Service
metadata:
  name: database-service
spec:
  type: LoadBalancer
  ports:
    - port: 1433  # External port
      targetPort: 1433  # Internal container port
  selector:
    app: database  # Should match your deployment's labels
