apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: gcr.io/docker2gcp/microservicesapplication-database
        ports:
        - containerPort: 1433
        env:
          - name: DB_USER
            value: "sqlserver"
          - name: DB_PASSWORD
            value: "Prakash2148@"
          - name: DB_HOST
            value: "104.196.127.218"
          - name: DB_NAME
            value: "mydatabase"